@startuml

[finiia（智能投资顾问，组合服务）] ..> [fincss（资金清算服务，资金清算系统）]
[finiia（智能投资顾问，组合服务）] <..> [finlcs（清算中心服务,业务清算系统）]
[finiia（智能投资顾问，组合服务）] ..> [finotsapp（运营终端前端）]
[finiia（智能投资顾问，组合服务）] ..> [finups（统一支付网关服务，支付网关）]


[fintcs（交易中心服务，销售系统）] ..> [fincss（资金清算服务，资金清算系统）]
[fintcs（交易中心服务，销售系统）] <..> [finlcs（清算中心服务,业务清算系统）]
[fintcs（交易中心服务，销售系统）] ..> [finotsapp（运营终端前端）]
[fintcs（交易中心服务，销售系统）] ..> [finups（统一支付网关服务，支付网关）]



[finotsapp（运营终端前端）] ..> [finots-server（运营终端后端）]
[finots-server（运营终端后端）] ..> [finlcs（清算中心服务,业务清算系统）]
[finots-server（运营终端后端）] ..> [fintcs（交易中心服务，销售系统）]
[finots-server（运营终端后端）] ..> [finiia（智能投资顾问，组合服务）]

cloud APP
cloud 机构通
cloud 柜台

[APP] ..> [finiia（智能投资顾问，组合服务）]: 前后端对接
[APP] ..> [fintcs（交易中心服务，销售系统）]: 前后端对接

[机构通] ..> [finiia（智能投资顾问，组合服务）]: 前后端对接
[机构通] ..> [fintcs（交易中心服务，销售系统）]: 前后端对接

[柜台] ..> [finiia（智能投资顾问，组合服务）]: 前后端对接
[柜台] ..> [fintcs（交易中心服务，销售系统）]: 前后端对接


cloud advisor投顾系统

[finiia（智能投资顾问，组合服务）] <..> [advisor投顾系统]
[fintcs（交易中心服务，销售系统）] <..> [advisor投顾系统]


database 深证通文件系统
[advisor投顾系统] <..> [深证通文件系统]
[finlcs（清算中心服务,业务清算系统）] <..> [深证通文件系统]
[深证通文件系统] --> 南方投顾组合
[深证通文件系统] --> 盈米投顾组合
[深证通文件系统] --> 易方达TA
[深证通文件系统] --> 南方TA
[深证通文件系统] --> 华夏TA
[深证通文件系统] --> 其他TA


cloud 支付通讯机
cloud 订单通讯机
cloud TA订单系统
cloud 外部支付系统

[finups（统一支付网关服务，支付网关）] <..> [支付通讯机]
[finups（统一支付网关服务，支付网关）] <..> [订单通讯机]
[订单通讯机] --> 创金
[订单通讯机] --> 信达
[订单通讯机] --> 东方红
[订单通讯机] --> 大成
[支付通讯机] --> 通联
[支付通讯机] --> 汇付
[支付通讯机] --> 块钱
[支付通讯机] --> 其他
[支付通讯机] ..> [外部支付系统]
[订单通讯机] ..> [TA订单系统]


@enduml
